# Generated by Django 2.2.2 on 2019-09-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
                ('is_parent', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('pathid', models.CharField(max_length=2048, null=True)),
                ('path', models.CharField(max_length=2048, null=True)),
            ],
            options={
                'db_table': 'wp_ex_source_goods_tb_cat_copy',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('hcode', models.CharField(default='', max_length=16)),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=1024)),
                ('shiling', models.IntegerField(choices=[(0, '夏季'), (1, '冬季'), (2, '常规')])),
                ('jibie', models.IntegerField(choices=[(0, '普通'), (1, '重点'), (2, '核心')], default=0)),
                ('pifa', models.IntegerField(choices=[(0, '不可批发'), (1, '可批发')], default=0)),
                ('state_caigou', models.IntegerField(choices=[(0, '待评审'), (1, '通过评审'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0)),
                ('state_paishe', models.IntegerField(choices=[(0, '待评审'), (1, '通过评审'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0)),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('concat', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagChangjing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagDingwei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_supplier_change', to='cpm.Good')),
                ('now_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_supplier_now_supplier', to='cpm.Supplier')),
                ('raw_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_supplier_raw_supplier', to='cpm.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('sku_code', models.CharField(max_length=32)),
                ('sku_name', models.CharField(max_length=32)),
                ('sku_image', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=32, null=True)),
                ('width', models.CharField(max_length=32, null=True)),
                ('height', models.CharField(max_length=32, null=True)),
                ('weight', models.CharField(max_length=32, null=True)),
                ('desc', models.CharField(max_length=1024, null=True)),
                ('price_jin', models.IntegerField(default=0)),
                ('price_pifa', models.IntegerField(default=0)),
                ('price_sale', models.IntegerField(default=0)),
                ('date_market', models.DateTimeField(null=True)),
                ('sku_good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpm.Good')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsSelectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('is_change_charger', models.BooleanField(default=False)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_select_charger', to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpm.Good')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_brand', to='cpm.GoodsBrand'),
        ),
        migrations.AddField(
            model_name='good',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_cate', to='cpm.Category'),
        ),
        migrations.AddField(
            model_name='good',
            name='changjing',
            field=models.ManyToManyField(related_name='changjings', to='cpm.TagChangjing'),
        ),
        migrations.AddField(
            model_name='good',
            name='charger',
            field=models.ManyToManyField(related_name='goods_charger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='good',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='good',
            name='dingwei',
            field=models.ManyToManyField(related_name='dingweis', to='cpm.TagDingwei'),
        ),
        migrations.AddField(
            model_name='good',
            name='suppiler',
            field=models.ManyToManyField(related_name='goods_suppiler', to='cpm.Supplier'),
        ),
        migrations.CreateModel(
            name='ChargerChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_charger_change', to='cpm.Good')),
                ('now_charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_now_charger', to=settings.AUTH_USER_MODEL)),
                ('raw_charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_raw_charger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_id'], name='wp_ex_sourc_parent__56ee5f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='wp_ex_sourc_level_e745bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('cid',)},
        ),
    ]
