# Generated by Django 2.2.2 on 2019-09-04 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargerchange',
            name='now_charger',
        ),
        migrations.AddField(
            model_name='chargerchange',
            name='now_charger',
            field=models.ManyToManyField(related_name='goods_now_charger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chargerchange',
            name='raw_charger',
        ),
        migrations.AddField(
            model_name='chargerchange',
            name='raw_charger',
            field=models.ManyToManyField(related_name='goods_raw_charger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='good',
            name='jibie',
            field=models.IntegerField(choices=[(0, '普通'), (1, '核心'), (2, '重点')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='shiling',
            field=models.IntegerField(choices=[(0, '常规'), (1, '冬季'), (2, '夏季')]),
        ),
 
        migrations.RemoveField(
            model_name='supplierchange',
            name='now_supplier',
        ),
        migrations.AddField(
            model_name='supplierchange',
            name='now_supplier',
            field=models.ManyToManyField(related_name='goods_supplier_now_supplier', to='cpm.Supplier'),
        ),
        migrations.RemoveField(
            model_name='supplierchange',
            name='raw_supplier',
        ),
        migrations.AddField(
            model_name='supplierchange',
            name='raw_supplier',
            field=models.ManyToManyField(related_name='goods_supplier_raw_supplier', to='cpm.Supplier'),
        ),
    ]
