# Generated by Django 2.2.2 on 2019-09-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0002_auto_20190904_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='number_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='p_cycle',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='price_is_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='sku_bar_code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chargerchange',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_charger_change', to='cpm.Good'),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '带创建新品'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_paishe',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '带创建新品'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sku_code',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sku_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_skus', to='cpm.Good'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sku_image',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sku_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplierchange',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_supplier_change', to='cpm.Good'),
        ),
        migrations.CreateModel(
            name='GoodsPingshenPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpm.Good')),
                ('pingshener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_pingshen_charger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
