# Generated by Django 2.2.2 on 2019-09-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0003_auto_20190906_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_paishe',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待入库'), (5, '待拍摄'), (6, '待制作'), (7, '待上架'), (8, '已上架'), (9, '待淘汰'), (10, '退市'), (11, '待封存'), (12, '待启封')], default=0),
        ),
        migrations.CreateModel(
            name='GoodsPurchasePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('purchase_date', models.DateTimeField(null=True)),
                ('expected_data', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_buy_buyer', to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_buy_good', to='cpm.Good')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_buy_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
