# Generated by Django 2.2.2 on 2019-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0004_auto_20190911_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodspurchasephase',
            name='desc',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
