# Generated by Django 2.2.2 on 2019-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0005_goodspurchasephase_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='state_raw',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '待制作'), (9, '待上架'), (10, '已上架'), (11, '待淘汰'), (12, '退市'), (13, '待封存'), (14, '待启封')], default=0),
        ),
        migrations.AddField(
            model_name='goodspurchasephase',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '待制作'), (9, '待上架'), (10, '已上架'), (11, '待淘汰'), (12, '退市'), (13, '待封存'), (14, '待启封')], default=4),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '待制作'), (9, '待上架'), (10, '已上架'), (11, '待淘汰'), (12, '退市'), (13, '待封存'), (14, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_paishe',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '待制作'), (9, '待上架'), (10, '已上架'), (11, '待淘汰'), (12, '退市'), (13, '待封存'), (14, '待启封')], default=0),
        ),
    ]
