# Generated by Django 2.2.2 on 2019-09-12 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0006_auto_20190912_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDianAndFenPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('state', models.IntegerField(choices=[(0, '正常'), (1, '缺货'), (2, '发错货'), (3, '其他')], default=0)),
                ('desc', models.CharField(max_length=1024, null=True)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_fen_dian_charger', to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_dian_fen', to='cpm.Good')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_fen_dian_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
