# Generated by Django 2.2.2 on 2019-09-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0007_goodsdianandfenphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '拍摄中'), (9, '待制作'), (10, '待上架'), (11, '已上架'), (12, '待淘汰'), (13, '退市'), (14, '待封存'), (15, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_paishe',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '拍摄中'), (9, '待制作'), (10, '待上架'), (11, '已上架'), (12, '待淘汰'), (13, '退市'), (14, '待封存'), (15, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='state_raw',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '拍摄中'), (9, '待制作'), (10, '待上架'), (11, '已上架'), (12, '待淘汰'), (13, '退市'), (14, '待封存'), (15, '待启封')], default=0),
        ),
        migrations.AlterField(
            model_name='goodspurchasephase',
            name='state_caigou',
            field=models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '拍摄中'), (9, '待制作'), (10, '待上架'), (11, '已上架'), (12, '待淘汰'), (13, '退市'), (14, '待封存'), (15, '待启封')], default=4),
        ),
        migrations.CreateModel(
            name='GoodsPhotoStartPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('detail_type', models.IntegerField(choices=[(0, '上新'), (1, '翻新')], default=0)),
                ('good_photo_method', models.IntegerField(choices=[(0, '外部拍摄'), (1, '内部拍摄')])),
                ('kuaidi_name', models.CharField(max_length=64, null=True)),
                ('kuaidi_code', models.CharField(max_length=128, null=True)),
                ('kuaidi_jdate', models.DateTimeField(null=True)),
                ('kuaidi_edate', models.DateTimeField(null=True)),
                ('desc', models.CharField(max_length=1024, null=True)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_detail_good', to='cpm.Good')),
                ('kuaidi_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_detail_kuaidi_sender', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_detail_operator', to=settings.AUTH_USER_MODEL)),
                ('photo_genzonger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_detail_genzonger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
