# Generated by Django 2.2.2 on 2019-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0008_auto_20190916_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsphotostartphase',
            name='is_need_jisong',
            field=models.BooleanField(default=False),
        ),
    ]
