# Generated by Django 2.2.2 on 2019-09-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0011_goodssysxingandfinishphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssysxingandfinishphase',
            name='photo_start',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_sysx_photo_start', to='cpm.GoodsPhotoStartPhase'),
        ),
    ]
