# Generated by Django 2.2.2 on 2019-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0012_goodssysxingandfinishphase_photo_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdianandfenphase',
            name='real_arrival_date',
            field=models.DateTimeField(null=True),
        ),
    ]
