# Generated by Django 2.2.2 on 2019-09-17 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0013_goodsdianandfenphase_real_arrival_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsYanhuoPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('result', models.IntegerField(choices=[(0, '合格'), (1, '不合格'), (2, '其他')])),
                ('video', models.CharField(max_length=256, null=True)),
                ('images', models.CharField(max_length=2048, null=True)),
                ('desc', models.CharField(max_length=1024, null=True)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_yanhuo_charger', to=settings.AUTH_USER_MODEL)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_yanhuo_good', to='cpm.Good')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_yanhuo_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
