# Generated by Django 2.2.2 on 2019-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0015_auto_20190918_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodspingshenphase',
            name='cancel',
            field=models.IntegerField(choices=[(0, '同类产品过多'), (1, '价格无优势'), (2, '供应保障问题'), (3, '上市时间问题'), (4, '知识产权问题'), (5, '无必要资质'), (6, '其他')], null=True),
        ),
        migrations.AddField(
            model_name='goodspingshenphase',
            name='desc',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='goodspingshenphase',
            name='wait',
            field=models.IntegerField(choices=[(0, '补充信息'), (1, '推迟评审'), (2, '其他')], null=True),
        ),
    ]
