# Generated by Django 2.2.2 on 2019-09-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0017_auto_20190924_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('code', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('code', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('avenue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avenue_shops', to='cpm.Avenue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
