# Generated by Django 2.2.2 on 2019-09-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpm', '0018_avenue_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_first_shangjia',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SkuToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('sku_in_shop_state', models.IntegerField(choices=[(0, '待评审'), (1, '待创建新品'), (2, '终止'), (3, '待采购'), (4, '待分货点货'), (5, '待验货'), (6, '待入库'), (7, '待拍摄'), (8, '拍摄中'), (9, '待制作'), (10, '待上架'), (11, '已上架'), (12, '待淘汰'), (13, '退市'), (14, '待封存'), (15, '待启封')], default=10)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku2shop_shop', to='cpm.Shop')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku2shop_sku', to='cpm.GoodsSku')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsShangjiaPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('shangjia_times', models.IntegerField(default=1)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_shangjia_sku', to='cpm.Good')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_shangjia_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
