# Generated by Django 2.2.2 on 2019-09-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0019_auto_20190926_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sub_name',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='goodsmgzzphase',
            name='mk_state',
            field=models.IntegerField(choices=[(0, '未分配'), (1, '已分配'), (2, '待审核'), (3, '制作完成')], default=0),
        ),
    ]
