# Generated by Django 2.2.2 on 2019-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0023_indexhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexhistory',
            name='caigou_exceed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexhistory',
            name='paishe_exceed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexhistory',
            name='ruku_exceed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexhistory',
            name='zhizuo_exceed',
            field=models.IntegerField(default=0),
        ),
    ]
