# Generated by Django 2.2.2 on 2019-11-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0024_auto_20191021_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonCategory',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2048)),
                ('is_parent', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('pathid', models.CharField(max_length=2048, null=True)),
                ('path', models.CharField(max_length=2048, null=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.AddIndex(
            model_name='soncategory',
            index=models.Index(fields=['parent_id'], name='t_category_parent__e7be5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soncategory',
            unique_together={('cid',)},
        ),
    ]
