# Generated by Django 2.2.2 on 2019-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0025_auto_20191112_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_multi_export',
            field=models.BooleanField(default=False),
        ),
    ]
