# Generated by Django 2.2.2 on 2019-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0026_good_is_multi_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
