# Generated by Django 2.2.2 on 2019-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0027_auto_20191119_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='desc',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='p_cycle',
            field=models.CharField(default='0', max_length=64, null=True),
        ),
    ]
