# Generated by Django 2.2.2 on 2019-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpm', '0028_auto_20191119_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='sku_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
